
### register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "username": "testuser",
  "password": "password123",
  "confirmPassword": "password123"
}


### login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}


### get user profile
GET http://localhost:3000/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3NDM0MjIyNDMsImV4cCI6MTc0MzQyNTg0M30.p1ghg5b0-yNHp0zhIRibpUoK0FddLQpQEiplbnb1QEs